version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GORM_HOST=rdbms
    depends_on:
      - rdbms
    volumes:
      - './:/SosApp'
    ports:
      - "80:80"

  rdbms:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - './.postgresql/:/var/lib/postgresql'
    ports:
      - '5432:5432'
