version: '3'

services:
  sos-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GORM_HOST=sosapp.ch2h0tcvltmv.ap-southeast-1.rds.amazonaws.com
      - GORM_PORT=5432
      - GORM_NAME=postgresdb
      - GORM_USER=postgres
      - GORM_PASS=pgpassword
    volumes:
      - './:/SosApp'
    ports:
      - "80:80"

#  rdbms:
#    image: postgres:latest
#    environment:
#      POSTGRES_DB: postgresdb
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: pgpassword
#    volumes:
#      - './.postgresql/:/var/lib/postgresql'
#    ports:
#      - '5432:5432'
