version: '3'

services:
  rdbms:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpassword
    volumes:
      - './.postgresql/:/var/lib/postgresql'
    ports:
      - '5432:5432'



  sos-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GORM_NAME=postgresdb
      - GORM_USER=postgres
      - GORM_PASS=pgpassword
      - GORM_HOST=rdbms
    volumes:
      - './:/SosApp'
    ports:
      - "80:80"

